### ISSUE TITLE
PEPISCMS_Form_validation CI object has null value

### ISSUE THREAD

**Issue by PerseiX** [piotrpolak/pepiscms#2]
When I try use custom validation method, with `callback_my_method` convention I get `form_validation__my_method` error. When I debug code, I found that in `PEPISCMS_Form_validation` class in the *__construct* variable *$module_instance* has null value.

**Comment by piotrpolak** [comment]
It turned out the $CI object was set prematurely when validation was loaded before the module action has been executed resulting in $CI object being set to Module controller.
